monitor.alsa.rules = [
  {
    # Komplete Audio 1 - output (headphones)
    matches = [
      { node.name = "~alsa_output.*Komplete_Audio_1*" }
    ]
    actions = {
      update-props = {
        audio.format          = "S32_LE"
        audio.rate            = 48000
        audio.allowed-rates   = [ 48000 96000 ]
        api.alsa.period-size  = 128
        api.alsa.period-num   = 3
        api.alsa.headroom     = 128
        session.suspend-timeout-seconds = 0
        node.pause-on-idle    = false
      }
    }
  }
  {
    # Komplete Audio 1 - input (mic)
    matches = [
      { node.name = "~alsa_input.*Komplete_Audio_1*" }
    ]
    actions = {
      update-props = {
        audio.format          = "S32_LE"
        audio.rate            = 48000
        audio.allowed-rates   = [ 48000 96000 ]
        api.alsa.period-size  = 128
        api.alsa.period-num   = 3
        api.alsa.headroom     = 128
        session.suspend-timeout-seconds = 0
        node.pause-on-idle    = false
      }
    }
  }
]
