cursor #f2dde7
cursor_text_color #d5c1cb

foreground            #f2dde7
background            #1b1017
selection_foreground  #482536
selection_background  #edb8cd
url_color             #ffade6

color0   #1b1017
color1   #ff727e
color2   #a4ff7f
color3   #ffdf72
color4   #f294d5
color5   #850073
color6   #ffade6
color7   #ffeffc
color8   #484047
color9   #ff9fa7
color10  #bfffa5
color11  #ffeba5
color12  #ffb9e9
color13  #ffc5ed
color14  #ffdaf3
color15  #fff8fe
