window_padding_width 0

confirm_os_window_close 0
enable_audio_bell no
allow_remote_control yes

cursor_blink_interval 0

background #000000
background_opacity 0.6

map ctrl+[ scroll_to_prompt -1
map ctrl+] scroll_to_prompt 1

# minimize kitty latency (higher energy usage)
input_delay 0
repaint_delay 2
sync_to_monitor no
wayland_enable_ime no

cursor_text_color #000000
