[package]
name = "micproc-jack"
version = "0.1.0"
edition = "2021"

[dependencies]
jack = "0.11.4"
arc-swap = "1"
serde = { version = "1", features = ["derive"] }
ron = "0.8"
notify = { version = "8", default-features = false }
nnnoiseless = "0.5.2"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
