effects = curves:vibrance
reshadeTexturePath = "/opt/reshade/textures"
reshadeIncludePath = "/opt/reshade/shaders"

vibrance = /opt/reshade/shaders/SweetFX/Vibrance.fx
curves = /opt/reshade/shaders/SweetFX/Curves.fx
denoise = /opt/reshade/shaders/Denoise.fx

Vibrance = 0.20
Curves = 0.15
