effects = curves:vibrance
reshadeTexturePath = "/opt/reshade/textures"
reshadeIncludePath = "/opt/reshade/shaders"

vibrance = /opt/reshade/shaders/SweetFX/Vibrance.fx
curves = /opt/reshade/shaders/SweetFX/Curves.fx

Vibrance = 0.20
Contrast = 0.65
Mode = 0
Formula = 4
