# vim:set ft=tmux:
%hidden MODULE_NAME="last_session"

set -g "@catppuccin_${MODULE_NAME}_icon" " "
set -gF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_overlay_1}"
set -g "@catppuccin_${MODULE_NAME}_text" " #{@previous_session_name}"

source -F "#{d:current_file}/../plugins/tmux/utils/status_module.conf"
