[colors.primary]
background = '#1b1017'
foreground = '#f2dde7'

[colors.selection]
text = '#f2dde7'
background = '#850073'

[colors.cursor]
text = '#1b1017'
cursor = '#ffade6'

[colors.normal]
black   = '#1b1017'
red     = '#ff727e'
green   = '#a4ff7f'
yellow  = '#ffdf72'
blue    = '#f294d5'
magenta = '#850073'
cyan    = '#ffade6'
white   = '#ffeffc'

[colors.bright]
black   = '#484047'
red     = '#ff9fa7'
green   = '#bfffa5'
yellow  = '#ffeba5'
blue    = '#ffb9e9'
magenta = '#ffc5ed'
cyan    = '#ffdaf3'
white   = '#fff8fe'
