[package]
name = "pw-links"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pw-links"
path = "src/main.rs"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3

[dependencies]
pipewire = { version = "0.10.1", features = ["v1_2_0"] }
serde = { version = "1", features = ["derive"] }
ron = "0.8"
